name: Continuous Integration

on:
  push:
    paths-ignore:
      - docs/**
      - README.md
  pull_request:
    paths-ignore:
      - docs/**
      - README.md

# https://github.com/uber/AutoDispose/blob/main/.github/workflows/ci.yml
jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      # https://github.com/Malinskiy/action-android
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.3
      - name: Build project
        run: ./gradlew assemble --stacktrace
      - name: Run unit tests
        run: ./gradlew test --stacktrace
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        with:
          cmd: ./gradlew connectedAndroidTest --stacktrace # the shell command to execute while the emulator is booted
          api: 28 # the API version of emulator
          tag: default # either the default or google_apis. Use google_apis for emulator with google store
          abi: x86 #  the abi of the emulator. x86 is the fastest one


