name: Continuous Integration

on:
  push:
    paths-ignore:
      - docs/**
      - README.md
  pull_request:
    paths-ignore:
      - docs/**
      - README.md

# https://github.com/uber/AutoDispose/blob/main/.github/workflows/ci.yml
jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 1.8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
      # https://github.com/Malinskiy/action-android
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.3
      - name: Build project
        run: ./gradlew assemble --stacktrace
      - name: Run unit tests
        run: ./gradlew test --stacktrace
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        with:
          cmd: ./gradlew connectedAndroidTest --stacktrace
          api: 25
          tag: default
          abi: x86


